name = "tezapi"
compatibility_date = "2024-06-23"

[vars]
UPSTASH_REDIS_REST_TOKEN = "AcV5AAIncDE3NTIzNjFjNWNiM2E0MjM1OGQwMzZkZDA1MTc1YjBjOXAxNTA1NTM"
UPSTASH_REDIS_REST_URL = "https://up-mammoth-50553.upstash.io"